# Generated by Django 4.0.5 on 2022-06-09 13:29

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_bfvcandidateballot_pailliercandidateballot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bfvcandidateballot',
            name='adams',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
        migrations.AlterField(
            model_name='bfvcandidateballot',
            name='jefferson',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
        migrations.AlterField(
            model_name='bfvcandidateballot',
            name='washington',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
        migrations.AlterField(
            model_name='pailliercandidateballot',
            name='adams',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
        migrations.AlterField(
            model_name='pailliercandidateballot',
            name='jefferson',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
        migrations.AlterField(
            model_name='pailliercandidateballot',
            name='washington',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
